export { PluginManager } from "./plugin-manager";
export type { Plugin, PluginAPI, PluginPanel, PluginToolbarButton, PluginMenuItem, PluginCommand } from "./types";
export { LoremIpsumPlugin, LoremIpsumPlugin as loremIpsumPlugin } from "./samples/lorem-ipsum";
export { ColorPalettePlugin, ColorPalettePlugin as colorPalettePlugin } from "./samples/color-palette";
export { GridGeneratorPlugin } from "./samples/grid-generator";
export { AutoRenamePlugin } from "./samples/auto-rename";
export { AccessibilityCheckerPlugin } from "./samples/accessibility-checker";
export { PLUGIN_CATALOG, searchCatalog, ALL_CATEGORIES } from "./catalog";
export type { CatalogEntry, PluginCategory } from "./catalog";
export { createFigmaCompat, runFigmaPlugin } from "./figma-compat";
export type { FigmaCompat } from "./figma-compat";
export { IframeSandbox, createSandboxedPlugin } from "./iframe-sandbox";
export type { PluginManifest, PluginPermission } from "./iframe-sandbox";
